[package]
name = "memkek"
version = "0.1.0"
authors = ["MetaMuffin <metamuffin@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
process-memory = "*"
sysinfo = "*"
regex = "*"
pretty-hex = "*"
hex = "*"
